---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
aireport:
  prompt-prefix-for-report: prompt_report
  prompt-prefix-for-report-name: prompt_repname
  function-for-json: prompt_json
  prompt-prefix-for-pcl: prompt_pcl
  function-for-pcl: func_pcl
  ai-core-destination: AICore
  function-for-cds: func_cds
  prompt-prefix-for-cds: prompt_cds

# logging:
#   level:
#     '[com.sap.cds.adapter.odata]': TRACE
#     '[com.sap.cds.odata.v4]': TRACE
#     '[com.sap.cds.persistence.sql]': TRACE
#     '[com.sap.cds.persistence.sql-tx]': TRACE
---
spring:
  config:
    activate:
      on-profile: default
  # sql:
    # init:
      # schema-locations: classpath:schema.sql
  web.resources.static-locations: file:./app/
cds:
  security:
    mock:
      users:
        admin:
          password: admin
          roles:
          - admin
          # "roles[0]": admin
        user:
          password: user
  data-source:
    auto-config:
      enabled: true


